### PR TITLE
Add topics for `#programming-pedagogy` channel

### LINKED ISSUE #1018: Add #programming-pedagogy topics to `.topic` command
## Description

@Shom770 had asked [here](https://discord.com/channels/267624335836053506/635950537262759947/936025673686986772) about potentially adding the topics mentioned [here](https://discord.com/channels/267624335836053506/934931964509691966/934931998366130238) to the `.topic` command and I think it should be done.

## Reasoning

Not sure exactly how to explain the reasoning, but I personally think that there is no reason _not_ to add some topics from the `#programming-pedagogy` channel to the `.topic` command.

## Proposed Implementation

To implement this, I believe what we need to do is simply add the following block of code to the top of [this file](https://github.com/python-discord/sir-lancebot/blob/main/bot/resources/utilities/py_topics.yaml):
```
#programming-pedagogy
934931964509691966:
    - topic1
    - topic2
    - etc.
```
EDIT: I just realized simply adding that block of code to the top of the YAML file may not work because `#programming-pedagogy` is not in the topical chat category on Discord. If that's the case, would appreciate it if someone could tell me how to correctly add those topics.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

### PR DESCRIPTION
**Pull request by DMFriends**
## Relevant Issues
Closes #1018 

## Description

This PR adds topics to the `.topic` command for the new `#programming-pedagogy` channel that was recently added.

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

### CODE REVIEW

**Comment by minalike** [comment]
Besides perhaps the third question, these questions/topics are not well-suited for the `.topic` command. These were suggestions provided by @swfarnsworth as a primer or introduction to what pedagogy is about. However, using these questions verbatim that mention non-specific X and Ys would not be conducive to starting a discussion in that channel.

**Comment by DMFriends** [comment]
> Besides perhaps the third question, these questions/topics are not well-suited for the `.topic` command. These were suggestions provided by @swfarnsworth as a primer or introduction to what pedagogy is about. However, using these questions verbatim that mention non-specific X and Ys would not be conducive to starting a discussion in that channel.

Oh alright, I see what you mean. I could try to think of some more specific ones then.

**Review by lemonsaurus — APPROVED** [review]
I think these seem okay. It would be nice if there were more, but I don't have any problem with these being added. 🦆

**Review by ChrisLovering — APPROVED** [review]
Looks good 👌

**Comment by ChrisLovering** [comment]
disabled automerge as I cannot merge main into this branch since the enable commits from maintainers wasn't enabled on the PR. Once this branch is updated to main, we can merge it.

**Pull request merged**
