### PR TITLE
some new questions

### PR DESCRIPTION
**Pull request by AnkithAbhayan**
new questions

## Did you:

- [ ] Join the [**Python Discord Community**](https://discord.gg/python)?
- [ ] If dependencies have been added or updated, run `pipenv lock`?
- [ ] **Lint your code** (`pipenv run lint`)?
- [ ] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Comment by Shivansh-007** [comment]
We cab use the [Open Trivia DB](https://opentdb.com/api_config.php) api to get quesitions instead, this would be a much better way and we won't need to add the trivia question manually.

Example: https://opentdb.com/api.php?amount=5&category=18&difficulty=medium&type=multiple

**Comment by HassanAbouelela** [comment]
Note on using the Open Trivia api:
The site indicates that the questions are licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/), which stipulates we:
> Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

More stipulations apply if we modify the questions, view CC website for more details.

**Comment by RohanJnr** [comment]
I think one of our concerns of Open Trivia DB was that anyone could add questions and that would affect the quality of the questions. I am not sure if there is any moderation that goes into actually adding the questions tho.

**Comment by HassanAbouelela** [comment]
I created an account while checking it out yesterday, and submitted a question. The questions get added after a manual review. That being said, I did have a look over the existing questions, and it seemed the moderation on them was quite lax, provided they put in some effort.

**Review by Xithrius — APPROVED** [review]

**Review by RohanJnr — APPROVED** [review]

**Pull request merged**
