### PR TITLE
Fix issues with repos not working when typing repo#num

### PR DESCRIPTION
**Pull request by vcokltfre**
## Description
Currently repos such as quackstack don't work with the issues cog when typing, for example, quackstack#29 into discord, since by default GitHub paginates repos to 30 per page, and we only fetch one page.

## Reasoning
Reasoning is to make the functionality work for repos beyond the 30 repo pagination limit, by adding a per_page query string to get 100 per page. This is not a permanent fix, but it should certainly suffice for a long time - another 64 repos.

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Review by ToxicKidz — APPROVED** [review]
:shipit:

**Review by dawnofmidnight — APPROVED** [review]
:shipit:

**Review by codephile1221 — APPROVED** [review]
LGTM, :shipit: .

**Comment by Akarys42** [comment]
Retargetting this to #642

**Review by Akarys42 — APPROVED** [review]
LGTM; thanks!

**Pull request merged**
