### PR TITLE
Fix issue matching regex

### PR DESCRIPTION
**Pull request by laundmo**
fixes it being unable to get issue numbers larger than 9
limits it somewhat length-wise and character-wise to the actual github limits

## Description
Changed the regex to match numbers at the end greedily
Changed the regex to only match allowed characters

## Additional Details
regex used: https://regex101.com/r/V2ji8M/6

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [ ] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Review by vcokltfre — APPROVED** [review]
LGTM regex is tested and working, more than can be said for the current one lol

**Review by onerandomusername — APPROVED** [review]
:shipit:

**Comment by laundmo** [comment]
> :shipit:

grafik

**Review by dawnofmidnight — APPROVED** [review]
The regEx works. :shipit:

**Review by jb3 — APPROVED** [review]
🚢

**Pull request merged**
