### PR TITLE
Upgrade override

### PR DESCRIPTION
**Pull request by HassanAbouelela**
## Description

This PR removes the in_channel_override, with the more feature-rich whitelist_check. This allows for more granularity with the checks. Other improvements include allowing commands to ignore the global checks if need be.

The improvements will not materialize immediately in this PR, but it will help other currently open PRs in implementing features smartly.

## Reasoning

The whitelist_check allows the checks to utilize categories, and roles, whereas previously category checks weren't possible, and role checks weren't available to the overrides.

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] **Lint your code** (`pipenv run lint`)?

### CODE REVIEW

**Review by Shivansh-007 — APPROVED** [review]
Can you also change the over-ride for [`.cht`](https://github.com/python-discord/sir-lancebot/blob/master/bot/exts/evergreen/cheatsheet.py) command?

**Comment by HassanAbouelela** [comment]
> Can you also change the over-ride for [`.cht`](https://github.com/python-discord/sir-lancebot/blob/master/bot/exts/evergreen/cheatsheet.py) command?

Thanks, I've gone ahead and fixed that.

**Review by Shivansh-007 — APPROVED** [review]
Nicely Done! LGTM (Tested locally)

**Review by ks129 — APPROVED** [review]

**Review by Xithrius — APPROVED** [review]
Tested. It works well. Thanks for this contribution!

**Pull request merged**
