### PR TITLE
Fixed  Battleship game ends abruptly if given bad input #622

### LINKED ISSUE #622: Battleship game ends abruptly if given bad input
## Description
Entering `I9ASDF` causes the .battleship game to error and end. 

## Steps to Reproduce
Start a game, enter a valid target, then add more to the message before sending it. Any text will do.

## Expected Behaviour
The bot to respond with a red X like it does for non-matching input (such as `AAAA`)

## Actual Behaviour
The game ends abruptly with `An error occurred. Game failed`

## Possible Solutions/Details
The core issue lies on this line: 
https://github.com/python-discord/sir-lancebot/blob/3454a88a43bec5d0959495c99b28ed80e96f12fb/bot/exts/evergreen/battleship.py#L262 and this line https://github.com/python-discord/sir-lancebot/blob/3454a88a43bec5d0959495c99b28ed80e96f12fb/bot/exts/evergreen/battleship.py#L230
Specifically, re.Match.string returns the entire text given to match against, and we're using re.match not re.fullmatch. Therefore, any message that contains a match is returned in entirety, rather than the match itself (which could be a portion of the message). 

We should probably use re.fullmatch instead. 

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

### PR DESCRIPTION
**Pull request by rijusougata13**
## Relevant Issues

Closes python-discord#622

## Description

self.match = re.fullmatch("([A-J]|[a-j]) ?((10)|[1-9])", message.content.strip())
I changed the regular expression match to full match .

## Reasoning

Basically pattern.match will return if any prefix of that pattern matches.
pattern.fullmatch will return true when the whole string matches

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [ ] If dependencies have been added or updated, run `pipenv lock`?
- [ ] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Comment by ks129** [comment]
@rijusougata13 Thanks for your contribution! Please fill pull request template fully and give why and what you changed. Thanks.

**Comment by rijusougata13** [comment]
@ks129  is it okay now?

**Review by ks129 — APPROVED** [review]
Thanks!

**Comment by rijusougata13** [comment]
so then we can merge and close the issue

**Review by ChrisLovering — APPROVED** [review]

**Pull request merged**
