### PR TITLE
Lowered input in catify

### PR DESCRIPTION
**Pull request by Kronifer**
## Relevant Issues

Nothing, talked about in discord outside of pydis

## Description

added text.lower()

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Comment by onerandomusername** [comment]
> ## Relevant Issues
> 
> Nothing, talked about in discord outside of pydis

would you please kink to the relevant conversation? [object Promise]

**Comment by Kronifer** [comment]
@onerandomusername turns out it was in pydis. Read [here](https://discord.com/channels/267624335836053506/291284109232308226/834104688169189396)

**Comment by jb3** [comment]
I think this better fits into #697. @ToxicKidz would you be cool with assessing this PR and incorporating necessary changes there?

**Comment by ToxicKidz** [comment]
Fixed in [this commit](https://github.com/python-discord/sir-lancebot/pull/697/commits/3477069a3a2e0b5e4030602afa4a4c0e7411a7e1).

**Comment by jb3** [comment]
Fantastic, thanks. I'll close this now.

**Pull request closed without merging**
