### PR TITLE
Create greetings.yml

### PR DESCRIPTION
**Pull request by ragr07**
###  Hello!

I would like to create a yml-file, a action on GitHub with greetings.

### CODE REVIEW

**Comment by MaskDuck** [comment]
why should this be added?

**Comment by ragr07** [comment]
Maybe extended friendliness.

**Comment by DMFriends** [comment]
@ragr07 You need to follow the contributing guidelines before opening a PR, you can find it at https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/contributing-guidelines/

**Comment by ragr07** [comment]
@DMFriends : It has resolved itself.

**Comment by DMFriends** [comment]
> @DMFriends : It has resolved itself.

Huh?

**Comment by ragr07** [comment]
Do you can close the issue, please?

**Comment by ragr07** [comment]
I found another solution.

**Comment by DMFriends** [comment]
> Do you can close the issue, please?

You can close it yourself by clicking the "Close Pull Request" button below the comment box.

**Pull request closed without merging**
