### PR TITLE
Better ping command

### PR DESCRIPTION
**Pull request by JagTheFriend**
### Updated ping command
Made a better ping command.

### After:
New 

### Important:
The bot will not reply to message(or to the sender of `.ping` command)
because I have removed that feature but I can add it back _if requested_

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [ ] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

### CODE REVIEW

**Comment by HassanAbouelela** [comment]
Hi, is there any context for this? Perhaps a conversation on discord or an issue on the repository?

As a side note, please don’t use the CI as your only linting. Run the lint locally, and maybe setup precommit to do it for you.

**Comment by JagTheFriend** [comment]
> Hi, is there any context for this? Perhaps a conversation on discord or an issue on the repository?

I just made the ping command of the bot more _stylish_ 
but to be honest, there isn't really a need for it.

> As a side note, please don’t use the CI as your only linting. Run the lint locally, and maybe setup precommit to do it for you.

I used the "format document" option you get within Vscode to format the file

**Comment by vcokltfre** [comment]
I made the original ping command simple because that's what I was asked to do. There was no desire nor need for an overly complex ping command, so I didn't implement one.

**Comment by JagTheFriend** [comment]
Alright.

**Pull request closed without merging**
