### PR TITLE
Update Tic Tac Toe Command

### PR DESCRIPTION
**Pull request by Shivansh-007**
## Description

1.  Update x and o emoji in `constants.Emojis` to use x and o instead of the letters x and o
2. Use embeds when you ask for board of a particular game, since it was pinging the user earlier. (`.ttt log show {game_id}`)

## Reasoning
Was approved by @Akarys42 

## Screenshots

Screenshot from 2021-03-15 16-05-09

Screenshot from 2021-03-15 16-05-20

## Did you:
- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Comment by RohanJnr** [comment]
is it possible to have the X and O to be of different colors? or is single color fine?

**Comment by Shivansh-007** [comment]
> is it possible to have the X and O to be of different colors? or is single color fine?

Hmm, there are no other colour of `x` and `o`. So i thought just to use this, since it is clearly differentiable.

**Review by HassanAbouelela — CHANGES_REQUESTED** [review]
Besides the change I requested, you have my tentative approval on the code.

In terms of actual functionality though, was the change in the `x` and `o` styles bikeshed? I don't particularly like the new ones, especially on light mode (you can compare the old and new styles in the screenshot below).

image

**Review by ToxicKidz — APPROVED** [review]

**Comment by HassanAbouelela** [comment]
This PR has been sitting here for many months now. All it does now is change one emoji for another, amongst the changes to the result. The changes to the result are fine, but I don't like the new emojis. Ultimately, that is a matter of preference, and I don't see how you could change that. I'll dismiss my review because while I don't agree with these changes, I won't block them either.

But here's the deal, let's not make minimal style changes like these anymore without at least discussing them, and coming to a consensus first, otherwise, we end up in this neverending pending state.

**Review by kosayoda — APPROVED** [review]
I see no point in letting this sit further, so I'll be merging this. I wholeheartedly agree with Scale, so keep his points in mind for future PRs.

**Pull request merged**
