### PR TITLE
Restructure Sir Lancebot

### LINKED ISSUE #841: Restructure Lancebot's exts/ folder
## Description
Sir-Lancebot, way back in the day, was created around seasons. We'd have things associated with Christmas, Easter, Valentine's Day, and then year-round things that we put under the "Evergreen" folder. With the growth of our community, Sir Lancebot has since outgrown this structure.

I'd like to re-organize Lancebot to be more general and less revolving around seasons.

## Reasoning
I think restructuring it to not be focused around seasons will make Lance's structure easier to understand for first-time contributors. I think the restructure I propose will make it easier to find things as well. Our `Evergreen` folder is quite large and can be a bit daunting to navigate.

## Proposed Implementation
This is my proposed general folder structure:
```
exts/
--adventofcode/
--holidays
    --hanukkah.py
    --easter/
    --valentines/
    --halloween/
    --pride/
--games/
    --all of our infinite games I'm not going to list out
--practical/ (this name is subject to change pending discussion)
    --wikipedia
    --wolfram
    --realpython
    --pythonfacts
--esoteric_challenges/
--trivia/
    --trivia_quiz
    --trivia_night
```
This is by no means an exhaustive list, but hopefully you get an understanding of the proposed structure changes.

## Additional Details
We currently have a `utils` folder. This will be renamed to `core` and then the `practical` folder listed above will be renamed to `utilities`. This is currently pending core-dev discussions.

This will probably significantly affect all current open PRs since it's changing the structure of things.

## Would you like to implement this yourself?
- [X] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

(If someone feels super strongly about this I'm also happy to pass it along, but I'm hoping to get this done and tested this weekend)

### LINKED ISSUE #846: AttributeError: 'Member' object has no attribute 'avatar_url'
Sentry Issue: [SIR-LANCEBOT-67](https://sentry.io/organizations/python-discord/issues/2618379582/?referrer=github_integration)

```
AttributeError: 'Member' object has no attribute 'avatar_url'
  File "discord/ext/commands/core.py", line 167, in wrapped
    ret = await coro(*args, **kwargs)
  File "bot/exts/evergreen/avatar_modification/avatar_modify.py", line 272, in prideavatar
    await self.send_pride_image(ctx, image_bytes, pixels, flag, option)
  File "bot/exts/evergreen/avatar_modification/avatar_modify.py", line 242, in send_pride_image
    embed.set_footer(text=f"Made by {ctx.author.display_name}.", icon_url=ctx.author.avatar_url)

Unhandled command error: 'Member' object has no attribute 'avatar_url'
```

### PR DESCRIPTION
**Pull request by janine9vn**
## Relevant Issues
Closes #841, closes #846 

## Description
This substantially changes the `exts/` structure for Lancebot. This moves us way from the seasons approach to something more generic and (hopefully) easier to understand for first-time contributors. The `resources/` folder also mimics the `exts/` folder.

The `exts/` folder now has the following subfolders:
```
avatar_modification/
core/
events/
fun/
holidays/
utilities/
```
`Avatar_Modification` was kept as a high-level ext because it is a rather unique extension that spans both holidays and general fun commands.
`Core` contains the commands import to the bot itself (i.e. ping, source, int e).
`Events` contains the commands related to events that we participate in (AoC).
`Fun` is the general folder for all the games and other fun commands.
`Holidays` contains the code previously associated with seasons (i.e. Halloween, Easter).
`Utilities` contains the commands that are useful/practical (i.e. realpython, wikipedia, stackoverflow, bookmark)

Two minor fixes for existing commands is also included in this PR.
The first is a fix for `.pridepfp`. The second is a temporary fix for the `.ddg` game.

## Did you:

- [X] Join the [**Python Discord Community**](https://discord.gg/python)? (lol)
- [X] Read all the comments in this template?
- [X] Ensure there is an issue open, or link relevant discord discussions?
- [X] Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

### CODE REVIEW

**Review by ChrisLovering — CHANGES_REQUESTED** [review]
Below is a list of places that will also need updating:

- https://github.com/python-discord/sir-lancebot/blob/main/bot/utils/extensions.py#L39
- https://github.com/python-discord/sir-lancebot/blob/main/bot/utils/halloween/spookifications.py#L25
- https://github.com/python-discord/sir-lancebot/blob/main/bot/utils/halloween/spookifications.py#L40
- All of the image urls in https://github.com/python-discord/sir-lancebot/blob/main/bot/resources/halloween/spooky_rating.json

**Review by ChrisLovering — APPROVED** [review]
👌 :shipit:

**Review by Kronifer — APPROVED** [review]
:+1:

**Review by D0rs4n — APPROVED** [review]
I went through all of the commands, and I couldn't find anything besides the ones mentioned(and patched) before.

**Review by doublevcodes — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
