### PR TITLE
Reset valentine command cooldown on failure

### PR DESCRIPTION
**Pull request by ChrisLovering**
## Description

By raising `UserInputError` the `on_command_error` listener `bot/exts/evergreen/error_handler:43` will reset the command cooldown and output a usage embed. By passing the error message as a string to `UserInputError` it now gets displayed within the same embed, rather than two messages.

## Reasoning

The reset cd already exists functionality, so raising the error utilizes already implemented & tested code.

## Screenshots
Usage embed when sending to yourself
image

 Usage embed when sending to someone with DMs disabled
image

Usage embed when sending to someone without lovefest role
image

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Review by Shivansh-007 — CHANGES_REQUESTED** [review]
Instead of sending two messages, can we just send one and include the msg in the description. You can pass in the `msg` while raising the error in the parameter `meaaage`

**Review by Shivansh-007 — COMMENTED** [review]
Hmmmm, can we send the error in DMs?

**Comment by ChrisLovering** [comment]
> Hmmmm, can we send the error in DMs?

There was only 1 error being sent to the author via DM before, which wasn't needed as we delete the message anyway. The less reason we give users to DM the bot the better.

**Review by Shivansh-007 — APPROVED** [review]
Not sure of the above, rest everything looks good. LGTM!

**Review by RohanJnr — APPROVED** [review]
looks good, tested too.

**Review by ks129 — APPROVED** [review]

**Pull request merged**
