### PR TITLE
fix: Handle a KeyError when using .quiz stop

### LINKED ISSUE #739: Quiz cog KeyError
Sentry Issue: [SIR-LANCEBOT-59](https://sentry.io/organizations/python-discord/issues/2401932701/?referrer=github_integration)

```
KeyError: 541638762007101470
  File "discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "bot/exts/evergreen/trivia_quiz.py", line 478, in stop_quiz
    del self.game_owners[ctx.channel.id]

Unhandled command error: 541638762007101470
```

Caused when multiple users with permission try to stop the same quiz.

### PR DESCRIPTION
**Pull request by ToxicKidz**
## Relevant Issues

Closes #739 

## Description

This PR handles a `KeyError` in a race condition for `.quiz stop`. Just a `try/except`.

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

### CODE REVIEW

**Review by fisher60 — APPROVED** [review]
LGTM, everything is working as expected.

**Review by Objectivitix — CHANGES_REQUESTED** [review]
There's a redundant `is True` on line 469 that I didn't see upon my first PR, would you mind removing that as well?

**Review by Kronifer — APPROVED** [review]
Aight, Looks good!

**Review by ChrisLovering — APPROVED** [review]

**Comment by ChrisLovering** [comment]
waiting for Github actions issue to be over since https://github.com/python-discord/sir-lancebot/pull/740 is ahead of this to be merged and this will need to be updated to main

**Pull request merged**
