### PR TITLE
replace image_url with source_image_url in spookygif.py

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
## Relevant Issues

https://github.com/python-discord/sir-lancebot/issues/1050#issuecomment-1116368854

## Description

replace image_url with source_image_url in spookygif.py

## Did you:

Yes

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

### CODE REVIEW

**Comment by SaumyaBhushan** [comment]
Please review?

**Review by wookie184 — CHANGES_REQUESTED** [review]
I get this error when trying to run this
```
KeyError: 'source_image_url'
```
I also don't see `source_image_url` mentioned anywhere in the documentation, so i'm not sure where this is from. Could you have another look at this? I gave a potential solution in the issue although ideally that should be tested before commiting.

**Comment by Xithrius** [comment]
@SaumyaBhushan will you be able to fix up this PR?

**Comment by SaumyaBhushan** [comment]
@Xithrius Sorry, I am unable to set up the project due to some issues. So I can't test it locally before committing. I will not be able to work on this.

**Comment by wookie184** [comment]
> @Xithrius Sorry, I am unable to set up the project due to some issues. So I can't test it locally before committing. I will not be able to work on this.

Alright, i'll close this PR and set the original Issue as up for grabs again. If you're interested in trying to set up the project in the future feel free to join the discord server and we can help with any issues.

**Pull request closed without merging**
