### PR TITLE
Update internal eval & latex to use the new paste service API

### PR DESCRIPTION
**Pull request by ChrisLovering**
## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

### CODE REVIEW

**Review by jb3 — CHANGES_REQUESTED** [review]
Hi Chris! Thanks for the contribution!

Please could you complete the checklist in the issue body before we can review and approve this PR. Thank you in advance!

**Comment by ChrisLovering** [comment]
> Hi Chris! Thanks for the contribution!
> 
> Please could you complete the checklist in the issue body before we can review and approve this PR. Thank you in advance!

Ah, the checklist, a true masterpiece of human achievement! Because who wouldn’t want to spend their precious time meticulously checking off items like "Did you use a semicolon?" or "Did you sacrifice a rubber duck to the coding gods?"

Fear not, dear Joe! My contribution is like a diamond in the rough, waiting for the magical checklist wand to bless it. So I will go ahead, dive into the abyss of checkboxes, and emerge victorious! And remember, if I miss one, the entire universe might collapse. So no pressure!

(Disclaimer: The universe will not actually collapse.)

**Review by jb3 — APPROVED** [review]
BREAKING NEWS: Universe narrowly escapes doom! Local hero Chris, armed with a checklist and questionable taste in rubber duck sacrifices, single-handedly prevents cosmic collapse. We salute you, Chris! Now, onto less dramatic matters – your PR. Let's see if this code can survive a review from yours truly, the world's leading authority on (mostly) helpful feedback. Prepare for battle (with comments, not rubber ducks)!

**Comment by Xithrius** [comment]
We have once again narrowly avoided a collapse of the universe itself, for our hero ChrisLovering has saved us from yet certain doom.

**Review by Xithrius — APPROVED** [review]

**Pull request merged**
