### PR TITLE
Trivia: Fix misleading category description embed

### PR DESCRIPTION
**Pull request by hedyhli**
The current formatting for the `.quiz help` command is misleading, where the spaces causes the wrong categories descriptions to be matched.

imageimage

### CODE REVIEW

**Review by wookie184 — APPROVED** [review]
Looks good, though do you think it would be neater to have the description on the same line as the category name, since most of the category descriptions are pretty short? I've not tried it so i'm not sure though.

**Comment by hedyhli** [comment]
I experimented with that format but decided on this one because that way makes the list quite spaced out. This way is easier to scan from top to bottom.

I can definitely change it if there's a very good reason you see why putting it on the same line is better.

**Comment by hedyhli** [comment]
The other two formats, for reference:
image
image

**Comment by Xithrius** [comment]
I like the second one more

**Comment by hedyhli** [comment]
I have made it follow the more concise format (second screenshot) as per request from @Xithrius.

**Comment by hedyhli** [comment]
Diff of the force-pushed changes.
```diff
diff --git a/bot/exts/fun/trivia_quiz.py b/bot/exts/fun/trivia_quiz.py
index 6041d031..d624e0fe 100644
--- a/bot/exts/fun/trivia_quiz.py
+++ b/bot/exts/fun/trivia_quiz.py
@@ -625,7 +625,7 @@ class TriviaQuiz(commands.Cog):
 
         for cat, description in self.categories.items():
             embed.description += (
-                f"- **{cat.capitalize()}**\n{description.capitalize()}\n\n"
+                f"- **{cat.capitalize()}**: {description.capitalize()}\n"
             )
 
         return embed
```

**Review by wookie184 — APPROVED** [review]
👍

**Review by Xithrius — APPROVED** [review]
Thank

**Pull request merged**
