### PR TITLE
Time Command

### PR DESCRIPTION
**Pull request by scragly**
TODO:

- [ ] Limit to staff channels.
- [ ] Refine error handling.
- [ ] Refine timezone disambiguation prompts.
- [ ] Add common timezone command for seeing a set or current time for multiple members and yourself

### CODE REVIEW

**Comment by Xithrius** [comment]
Hello @scragly, what's the status of this feature? 

Will you be continuing it?

Thanks!

**Comment by scragly** [comment]
Yes

**Comment by Xithrius** [comment]
Hey @scragly, I hope you're doing well. 

Just checking up on this PR since it's been a couple months. How goes it?

**Comment by Xithrius** [comment]
With the new time formats and utilities, there may be some major rewriting needed for this PR.

If you do resume this, please feel free to re-open.

**Pull request closed without merging**
