### PR TITLE
Add lesser yellow to color list

### PR DESCRIPTION
**Pull request by brad90four**
## Relevant Issues

Add new helper role color to color list

## Did you:

- [ ] Join the [**Python Discord Community**](https://discord.gg/python)?
- [ ] Read all the comments in this template?
- [ ] Ensure there is an issue open, or link relevant discord discussions?
- [ ] Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

### CODE REVIEW

**Review by shenanigansd — CHANGES_REQUESTED** [review]
Please update to use more inclusive language.
All Helpers are created equal!!

**Review by Coffee-93 — APPROVED** [review]
Lesser Yellow it is.

**Comment by brad90four** [comment]
> Please update to use more inclusive language. All Helpers are created equal!!

This name was the most popular according to this [poll](https://discord.com/channels/267624335836053506/291284109232308226/1091528484846841856)

**Review by shenanigansd — APPROVED** [review]
> > Please update to use more inclusive language. All Helpers are created equal!!
> 
> This name was the most popular according to this [poll](https://discord.com/channels/267624335836053506/291284109232308226/1091528484846841856)

I see.
I disagree, but I'll let this go through and then make a community issue about updating the language.

**Review by wookie184 — APPROVED** [review]
sure, why not

**Pull request merged**
