### PR TITLE
Added "centisecond" in  trivia_quiz.json

### LINKED ISSUE #747: Question missing a possible correct answer in `trivia_quiz.py`
## Description
The following math question with ID of 228 should have one more possible correct answer in the database.

## Steps to Reproduce
1. input the command `.quiz math 30`.
2. wait for it to reach that question (randomly generated, might take a while)
3. input the answer "centisecond".

It won't recognize it as a correct answer.

## Expected Behaviour
It should recognize it as a correct answer.

## Actual Behaviour
It doesn't.
image

## Known Impacted Platforms

- [x] Web
- [x] Desktop
- [x] Android App
- [x] iOS App

## Possible Solutions
Just add "centisecond" after the answers in question 228 in the json

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

### PR DESCRIPTION
**Pull request by soham4abc**
This closes #747 

## Description
added "centisecond" to the json file.

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

### CODE REVIEW

**Review by Objectivitix — CHANGES_REQUESTED** [review]
LGTM, but those indents though... could you revert them back to their original state, please?

**Comment by soham4abc** [comment]
> LGTM, but those indents though... could you revert them back to their original state (2 spaces), please?

Yes of course

**Comment by soham4abc** [comment]
@Objectivitix  Please review I have made the requested changes.

**Review by Objectivitix — APPROVED** [review]
LGTM :shipit: :D

**Comment by Xithrius** [comment]
@soham4abc Please complete all checkbox items in the first post of this PR.

**Comment by soham4abc** [comment]
> @soham4abc Please complete all checkbox items in the first post of this PR.

Done

**Review by Xithrius — APPROVED** [review]
It works well.

**Review by kosayoda — APPROVED** [review]

**Pull request merged**
